use super::*;

// ---- tool definitions -----------------------------------------------------------------------

fn tool(
    name: &str,
    description: &str,
    properties: Value,
    required: &[&str],
    read_only: bool,
) -> Value {
    json!({
        "name": name,
        "description": description,
        "inputSchema": { "type": "object", "properties": properties, "required": required, "additionalProperties": false },
        "annotations": {
            "readOnlyHint": read_only,
            "destructiveHint": !read_only,
            "openWorldHint": false,
        },
    })
}

fn detail() -> Value {
    json!({ "type": "boolean", "description": "Return everything instead of the summary.", "default": false })
}

fn profile_arg() -> Value {
    json!({ "type": "string", "description": "Server profile name.", "default": "default" })
}

pub fn tool_definitions() -> Vec<Value> {
    vec![
        tool(
            "projects",
            "The solution's ThingWorx projects, their roots, their deploy order and how many entity documents each holds.",
            json!({}),
            &[],
            true,
        ),
        tool(
            "types",
            "Generate editor declarations, type-check every service, or fetch and cache platform declarations. All actions take the workspace lock.",
            json!({
                "action": { "type": "string", "enum": ["generate", "check", "platform"], "default": "generate" },
                "profile": profile_arg(),
                "detail": detail(),
            }),
            &[],
            false,
        ),
        tool(
            "check",
            "Run every gate of the solution (line endings, sidecars in sync, formatting, script traps, code order, project validation, declared hooks). With live: true, every service script is also parsed by the ThingWorx server, and an unreachable server fails the check. live defaults to the solution's [gates] live.",
            json!({ "live": { "type": "boolean", "description": "Default: the solution's [gates] live." }, "profile": profile_arg(), "detail": detail() }),
            &[],
            true,
        ),
        tool(
            "status",
            "Compare entities with the server and the recorded baseline: in-sync, local-changed, server-changed, both-changed, not-on-server, or no baseline yet. Lists every entity that needs attention.",
            json!({
                "entity": { "type": "string", "description": "One entity name, full or its last dotted segment. Name one, or pass all: true." },
                "all": { "type": "boolean", "default": false, "description": "Every entity (of the project, if one is named)." },
                "project": { "type": "string", "description": "Narrow to one project of the solution." },
                "record": { "type": "boolean", "default": false, "description": "Record a baseline for every entity whose two sides agree. Writes .twaco/baseline.json under the workspace lock." },
                "profile": profile_arg(),
                "detail": detail(),
            }),
            &[],
            false,
        ),
        tool(
            "sync",
            "Write sidecars back into their entity XML: service scripts, DataShape fields, mashup content, DataTable configuration. This is how an edit to a script.js takes effect. check: true reports what would change and writes nothing. Takes the workspace lock while it writes.",
            json!({
                "entity": { "type": "string", "description": "One entity, full name or its last dotted segment. Name one, or pass all: true." },
                "all": { "type": "boolean", "default": false, "description": "Every entity (of the project, if one is named)." },
                "project": { "type": "string", "description": "Narrow to one project of the solution." },
                "check": { "type": "boolean", "default": false },
                "allow_add_remove": { "type": "boolean", "default": false, "description": "Permit a service or field to appear or disappear." },
                "relayout": { "type": "boolean", "default": false, "description": "Rewrite every script payload in the configured layout." },
            }),
            &[],
            false,
        ),
        tool(
            "extract",
            "Entity XML to sidecars: service scripts, DataShape fields, mashup content, DataTable configuration. Overwrites the sidecars of the entities chosen; takes the workspace lock.",
            json!({
                "entity": { "type": "string", "description": "One entity, full name or its last dotted segment. Name one, or pass all: true." },
                "all": { "type": "boolean", "default": false, "description": "Every entity (of the project, if one is named)." },
                "project": { "type": "string" },
            }),
            &[],
            false,
        ),
        tool(
            "fmt",
            "Format every service script sidecar with the built-in formatter. check: true reports which would change and writes nothing.",
            json!({ "check": { "type": "boolean", "default": false } }),
            &[],
            false,
        ),
        tool(
            "push",
            "Import one entity's file to the server. Refuses when the server changed since the last sync, was deleted there, or has no baseline, unless force is true. Reads the entity back and records a baseline only for what the server kept. A dry run unless dry_run is false.",
            json!({
                "entity": { "type": "string" },
                "dry_run": { "type": "boolean", "default": true },
                "force": { "type": "boolean", "default": false },
                "backup": { "type": "boolean", "default": true, "description": "With force, save the server's copy under .twaco/backups first (default true); false skips it." },
                "profile": profile_arg(),
            }),
            &["entity"],
            false,
        ),
        tool(
            "entity_delete",
            "Delete server entities in dependency-safe order. Accepts Collection/Name or a bare name resolved on the server; renamed adds undeleted entity/prefix entries from .twaco/renames.json. allow_repository_defined accepts a repository definition that deployment would recreate; allow_outside_dependents accepts structural dependents outside the delete set; allow_file_repository_data_loss accepts deleting a FileRepository Thing and all its files. A FileRepository delete needs its own acknowledgement. force is deprecated: it means the first two acknowledgements and never FileRepository data loss. A dry run unless dry_run is false; every applied delete is confirmed absent.",
            json!({
                "entities": { "type": "array", "items": { "type": "string" }, "description": "Entities to delete; may be empty when renamed is true." },
                "renamed": { "type": "boolean", "default": false },
                "allow_repository_defined": { "type": "boolean", "default": false },
                "allow_outside_dependents": { "type": "boolean", "default": false },
                "allow_file_repository_data_loss": { "type": "boolean", "default": false },
                "force": { "type": "boolean", "default": false, "description": "Deprecated: means allow_repository_defined and allow_outside_dependents; never accepts FileRepository data loss." },
                "dry_run": { "type": "boolean", "default": true },
                "backup": { "type": "boolean", "default": true, "description": "Save the server's copy of every entity under .twaco/backups before deleting (default true); a failed backup deletes nothing." },
                "profile": profile_arg(),
            }),
            &[],
            false,
        ),
        tool(
            "entity_restore",
            "List the backup sets taken before deletes and forced overwrites (no set given), or import one back: all its entities, or the named ones. A dry run unless dry_run is false; each import is confirmed on the server.",
            json!({
                "set": { "type": "string", "description": "A set id from the listing; omit to list sets." },
                "entities": { "type": "array", "items": { "type": "string" }, "description": "Only these (Collection/Name or a bare name)." },
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
            }),
            &[],
            false,
        ),
        tool(
            "entity_carry",
            "Copy run-time, design-time and visibility permissions from renamed (old) entities to the ones that replaced them, mapping principals through the rename ledger. pairs is a flat list [old, new, old, new, ...] of Collection/Name; renamed adds every pending ledger entity. A dry run unless dry_run is false; every write is read back and the ledger marked carried.",
            json!({
                "pairs": { "type": "array", "items": { "type": "string" }, "description": "Collection/Old, Collection/New, in pairs; may be empty when renamed is true." },
                "renamed": { "type": "boolean", "default": false },
                "dry_run": { "type": "boolean", "default": true },
                "detail": { "type": "boolean", "default": false, "description": "Also ask the platform for its own difference count." },
                "profile": profile_arg(),
            }),
            &[],
            false,
        ),
        tool(
            "db_run",
            "Run one SQL script as an atomic SQLCommand through a throwaway Database Thing. Plans by default and shows the SQL and sanitized connection target; pass dry_run: false to execute.",
            json!({
                "file": { "type": "string", "description": "A UTF-8 SQL file relative to the solution; give file or sql." },
                "sql": { "type": "string", "description": "Inline SQL; give sql or file." },
                "thing": { "type": "string", "description": "Database Thing; otherwise resolve the one in the solution." },
                "no_transaction": { "type": "boolean", "default": false, "description": "Prefix COMMIT; for statements such as CREATE DATABASE." },
                "timeout": { "type": "integer", "minimum": 1, "default": 120 },
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
            }),
            &[],
            false,
        ),
        tool(
            "db_query",
            "Run read-only SQLQuery through a throwaway Database Thing. Returns columns and the first 20 rows unless detail is true.",
            json!({
                "file": { "type": "string", "description": "A UTF-8 SQL file relative to the solution; give file or sql." },
                "sql": { "type": "string", "description": "Inline SQL; give sql or file." },
                "thing": { "type": "string", "description": "Database Thing; otherwise resolve the one in the solution." },
                "max_rows": { "type": "integer", "minimum": 1, "default": 500 },
                "timeout": { "type": "integer", "minimum": 1, "default": 120 },
                "profile": profile_arg(),
                "detail": detail(),
            }),
            &[],
            true,
        ),
        tool(
            "datatable_copy",
            "Copy the rows of one DataTable into the DataTable that replaced it, mapping fields by name, by the rename ledger, or by map ({old: new}). Refuses unmapped fields (unless drop_unmapped), type changes, and a non-empty target (unless append). A dry run unless dry_run is false; the target is read back and compared. Each row's source, tags and timestamp are not carried.",
            json!({
                "old": { "type": "string", "description": "The source DataTable's name." },
                "new": { "type": "string", "description": "The target DataTable's name." },
                "map": { "type": "object", "additionalProperties": { "type": "string" }, "description": "Source field to target field." },
                "drop_unmapped": { "type": "boolean", "default": false },
                "append": { "type": "boolean", "default": false },
                "max_rows": { "type": "integer", "minimum": 1, "default": 100000 },
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
            }),
            &["old", "new"],
            false,
        ),
        tool(
            "db_clean",
            "Find, and with dry_run false delete, the temporary ZZ.Twaco.Sql.* Database Things an interrupted db_run or db_query left on the server. Only names twaco generates, on Database Things, are touched.",
            json!({
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
            }),
            &[],
            false,
        ),
        tool(
            "deploy",
            "Deploy the solution: offline gates, one bundle per project in dependency order, every script parsed by the server (fails closed), a conflict check per entity, then import, read-back, and the project's deploy and post-import services. A dry run (a plan) unless dry_run is false.",
            json!({
                "dry_run": { "type": "boolean", "default": true },
                "force": { "type": "boolean", "default": false, "description": "Overwrite entities the server changed since the last sync." },
                "backup": { "type": "boolean", "default": true, "description": "With force, save the server's copy of each overwritten entity under .twaco/backups first (default true)." },
                "only": { "type": "array", "items": { "type": "string" }, "description": "Only these entities; post-import services are skipped." },
                "only_projects": { "type": "array", "items": { "type": "string" } },
                "backend_only": { "type": "boolean", "default": false },
                "skip_checks": { "type": "boolean", "default": false, "description": "Skip the offline gates. The server's script parse still runs." },
                "profile": profile_arg(),
                "detail": detail(),
            }),
            &[],
            false,
        ),
        tool(
            "adopt_report",
            "Compare a designer's Composer <Entities> export with the repository: which services it would revert, which entities it adds or changes (node by node with detail), and which it lacks. Writes nothing.",
            json!({
                "export": { "type": "string", "description": "Path to the export, absolute or relative to the solution root." },
                "entity": { "type": "array", "items": { "type": "string" }, "description": "Only entities whose name contains one of these." },
                "detail": detail(),
            }),
            &["export"],
            true,
        ),
        tool(
            "adopt_apply",
            "Adopt the mechanical half of a designer's export: mashup content into sidecars, a new mashup's entity file, changed media. Never writes a service or configuration table; run sync afterwards. Takes the workspace lock.",
            json!({
                "export": { "type": "string", "description": "Path to the export, absolute or relative to the solution root." },
                "entity": { "type": "array", "items": { "type": "string" } },
            }),
            &["export"],
            false,
        ),
        tool(
            "rename",
            "Rename one entity, a dotted project/building-block prefix, a DataShape field, a declared service, one service parameter, or a configuration table. A dry run unless dry_run is false; an apply takes the workspace lock. The result carries a plan_digest: pass it back with dry_run false to apply exactly the plan that was reviewed.",
            json!({
                "kind": { "type": "string", "enum": ["entity", "prefix", "field", "service", "param", "table", "property"] },
                "scope": { "type": "string", "description": "Entity full name; required for kind field, service or table." },
                "service": { "type": "string", "description": "Service name; required for kind param and refused otherwise." },
                "old": { "type": "string" },
                "new": { "type": "string" },
                "dry_run": { "type": "boolean", "default": true },
                "include_outside": { "type": "boolean", "default": false },
                "sql": { "type": "boolean", "default": false, "description": "Write the database migration script when the rename touches DBConnection tables (into sql/ or sql_dir). Such a rename is refused unless sql or no_sql is given." },
                "sql_dir": { "type": "string", "description": "Folder for the migration script, relative to the solution; implies sql." },
                "no_sql": { "type": "boolean", "default": false, "description": "The DBConnection tables are not in use: write no script." },
                "skip_checks": { "type": "boolean", "default": false },
                "plan_digest": { "type": "string", "description": "The plan_digest a dry run returned. With dry_run false, the rename is refused (nothing written) unless the plan is still exactly that one." },
            }),
            &["kind", "old", "new"],
            false,
        ),
        tool(
            "move_member",
            "Move or copy a service or a property from one Thing, template or shape to another in the repository: the definition (and a service's implementation and sidecar) is lifted out byte for byte and re-indented where it lands. Refuses a name the target, its ancestors or its descendants already use; reports the callers that stop resolving when the target is not something the source inherits; leave_delegate keeps a service on the source that calls the moved one (a Thing target). A dry run unless dry_run is false; an apply takes the workspace lock.",
            json!({
                "action": { "type": "string", "enum": ["move", "copy"] },
                "kind": { "type": "string", "enum": ["service", "property"] },
                "from": { "type": "string", "description": "The entity the member is on." },
                "to": { "type": "string", "description": "The entity it goes to." },
                "name": { "type": "string" },
                "new_name": { "type": "string", "description": "A new name on the target." },
                "leave_delegate": { "type": "boolean", "default": false },
                "dry_run": { "type": "boolean", "default": true },
            }),
            &["action", "kind", "from", "to", "name"],
            false,
        ),
        tool(
            "new_building_block",
            "Create a new building block in the repository, as the PTC Solution Framework's Create New Building Block does on a server: its project, EntryPoint template and Thing, Management shape, Manager template and Thing (not for an abstract block), default and admin groups and organization, as files, plus the project in twaco.toml. The files match what the framework produced on a server. The permission helper and the ui and test types are not created. A dry run unless dry_run is false; an apply takes the workspace lock.",
            json!({
                "name": { "type": "string", "description": "The block's name with its namespace, such as Acme.Orders." },
                "type": { "type": "string", "enum": ["standard", "abstract", "implementation"], "default": "standard" },
                "display_name": { "type": "string" },
                "description": { "type": "string" },
                "parent": { "type": "string", "description": "The abstract block an implementation implements." },
                "model_logic": { "type": "boolean", "default": false },
                "management_shape": { "type": "boolean", "default": true, "description": "An implementation may leave out its Management_TS." },
                "root": { "type": "string", "description": "The project's folder, relative to the solution; default the block's name." },
                "base_extension": { "type": "string", "description": "PTC.Base:<version>; default what another project of the solution declares." },
                "dry_run": { "type": "boolean", "default": true },
            }),
            &["name"],
            false,
        ),
        tool(
            "retemplate",
            "Change a Thing's template (or a template's base template) and/or the shapes it implements, in the repository. The plan lists what the entity and everything inheriting it gains and loses, the stored property values and configuration-table rows left with no definition, and the references to a lost member; such a loss is refused unless accept_loss is true. A dry run unless dry_run is false; an apply takes the workspace lock.",
            json!({
                "entity": { "type": "string", "description": "The Thing or template to change." },
                "template": { "type": "string", "description": "The new template (a Thing) or base template (a template)." },
                "add_shapes": { "type": "array", "items": { "type": "string" } },
                "remove_shapes": { "type": "array", "items": { "type": "string" } },
                "accept_loss": { "type": "boolean", "default": false },
                "dry_run": { "type": "boolean", "default": true },
            }),
            &["entity"],
            false,
        ),
        tool(
            "config_table",
            "Read one Thing's configuration table on the server, diff it against the entity XML in the repository, or restore it from a backup file. restore is a dry run unless dry_run is false; it refuses a backup of another Thing or table, and reads the table back.",
            json!({
                "thing": { "type": "string" },
                "table": { "type": "string" },
                "action": { "type": "string", "enum": ["read", "diff", "restore"], "default": "read" },
                "backup": { "type": "string", "description": "restore only: the backup file, as `twaco config-table --backup` writes it." },
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
                "detail": detail(),
            }),
            &["thing", "table"],
            false,
        ),
        tool(
            "logs",
            "Read a server log: ApplicationLog, ScriptLog, CommunicationLog, ConfigurationLog or SecurityLog. Newest first. A summary first (counts by level, top origins, repeated messages, the newest entries); detail: true lists every entry. truncated: true means the limit was reached.",
            json!({
                "log": { "type": "string", "description": "ApplicationLog, ScriptLog, CommunicationLog, ConfigurationLog or SecurityLog." },
                "since": { "type": "string", "default": "1h", "description": "How far back, ending now: a number and s, m, h or d. Not with from/to." },
                "from": { "type": "string", "description": "ISO-8601 with Z or an offset (2026-10-01T06:37:00Z); without one it is in the local time zone of the machine running twaco. Or `now`." },
                "to": { "type": "string", "description": "ISO-8601 or `now` (the default)." },
                "level": { "type": "string", "enum": ["TRACE", "DEBUG", "INFO", "WARN", "ERROR"], "description": "This level and above." },
                "grep": { "type": "string", "description": "Entries whose message contains this text." },
                "regex": { "type": "string", "description": "A Java regex that must match the whole message. Not with grep." },
                "user": { "type": "string" },
                "thread": { "type": "string" },
                "origin": { "type": "string" },
                "limit": { "type": "integer", "minimum": 1, "default": 200 },
                "oldest_first": { "type": "boolean", "default": false },
                "profile": profile_arg(),
                "detail": detail(),
            }),
            &["log"],
            true,
        ),
        tool(
            "log_level",
            "Read a server log's level and its subloggers' levels, or change one. ScriptLog at WARN records no logger.info or logger.debug from scripts; lower it while debugging, then put it back. A change is the whole server's and a dry run unless dry_run is false; the result says how to undo it.",
            json!({
                "log": { "type": "string", "description": "ApplicationLog, ScriptLog, CommunicationLog, ConfigurationLog or SecurityLog." },
                "level": { "type": "string", "enum": ["TRACE", "DEBUG", "INFO", "WARN", "ERROR"], "description": "Set this level. Omit, with reset false, to only read." },
                "sublogger": { "type": "string", "description": "A class or package within the log, such as com.thingworx." },
                "reset": { "type": "boolean", "default": false, "description": "Put the sublogger (or, without one, every sublogger) back to the log's level." },
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
            }),
            &["log"],
            false,
        ),
        tool(
            "repo",
            "Read the server's file repositories: list them, list a folder (recursive: true for everything below), get a text file's content, or compare the tree kept in source control (filerepository/<repo>/) with the server's (same, differs, local-only, remote-only; equal sizes are compared by SHA-256). Read-only.",
            json!({
                "action": { "type": "string", "enum": ["list", "ls", "get", "status"], "default": "list" },
                "repository": { "type": "string", "description": "A FileRepository Thing, such as SystemRepository. Not for list." },
                "path": { "type": "string", "description": "ls: a folder (default /); get: a file, such as Thumbnails/a.png." },
                "recursive": { "type": "boolean", "default": false },
                "max_chars": { "type": "integer", "minimum": 1000, "default": 100000, "description": "get: the most text returned." },
                "profile": profile_arg(),
                "detail": detail(),
            }),
            &[],
            true,
        ),
        tool(
            "repo_write",
            "Change a file repository: put (upload text, or a file of the solution), mkdir, rm (a file, or a folder; recursive: true to delete one that holds anything), mv (a file), or push/pull the tree kept in source control. A dry run unless dry_run is false. Nothing existing is replaced without overwrite: true; applied changes are read back.",
            json!({
                "action": { "type": "string", "enum": ["put", "mkdir", "rm", "mv", "push", "pull"], "description": "push/pull: the whole tree filerepository/<repo>/ to or from the server; neither deletes." },
                "repository": { "type": "string" },
                "path": { "type": "string", "description": "put/mkdir/rm: the repository path; mv: the source." },
                "to": { "type": "string", "description": "mv: the file's new path." },
                "text": { "type": "string", "description": "put: the content, as UTF-8 text." },
                "local": { "type": "string", "description": "put: a file of the solution to upload instead, relative to the solution root." },
                "overwrite": { "type": "boolean", "default": false },
                "recursive": { "type": "boolean", "default": false },
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
            }),
            &["action", "repository"],
            false,
        ),
        tool(
            "extensions",
            "The server's extension packages: list them, or show one (its extensions, and which are in use). Read-only.",
            json!({
                "action": { "type": "string", "enum": ["list", "show"], "default": "list" },
                "package": { "type": "string", "description": "show: the package name." },
                "profile": profile_arg(),
            }),
            &[],
            true,
        ),
        tool(
            "extension_write",
            "Import an extension package zip of the solution, or remove an installed package. A dry run unless dry_run is false: an import is then only validated by the server, which installs nothing. A removal is refused while the package is in use.",
            json!({
                "action": { "type": "string", "enum": ["import", "remove"] },
                "zip": { "type": "string", "description": "import: the package zip, relative to the solution root." },
                "package": { "type": "string", "description": "remove: the package name." },
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
            }),
            &["action"],
            false,
        ),
        tool(
            "export",
            "Export from the server as Composer's Import/Export does: an entity (Collection/Name), a collection (optionally one project's part), or a whole project, as one XML file written inside the solution; or the source-control layout of a project, collection or tags into a file repository folder or zip (a dry run unless dry_run is false).",
            json!({
                "action": { "type": "string", "enum": ["entity", "collection", "project", "source_control"] },
                "entity": { "type": "string", "description": "entity: Collection/Name, such as Things/My.Thing." },
                "collection": { "type": "string" },
                "project": { "type": "string" },
                "out": { "type": "string", "description": "entity/collection/project: the file to write, relative to the solution root." },
                "overwrite": { "type": "boolean", "default": false },
                "repository": { "type": "string", "description": "source_control: the file repository." },
                "path": { "type": "string", "description": "source_control: the folder in it." },
                "tags": { "type": "string" },
                "zip": { "type": "string", "description": "source_control: write a zip of this name instead of a folder." },
                "with_dependents": { "type": "boolean", "default": false },
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
            }),
            &["action"],
            false,
        ),
        tool(
            "package",
            "Package the repository for release, offline, into a file inside the solution: a bundle (one importable XML; part all, backend or frontend), a source-control zip (<Project>/<Collection>/<Name>.xml), or a DPM-style extension zip (one project's, or the solution's as a zip of its projects' zips; editable or not; metadata from [package] in twaco.toml).",
            json!({
                "action": { "type": "string", "enum": ["bundle", "source_control", "extension"] },
                "project": { "type": "string", "description": "Only this project; the whole solution when omitted." },
                "part": { "type": "string", "enum": ["all", "backend", "frontend"], "default": "all", "description": "bundle: which collections." },
                "editable": { "type": "boolean", "default": false, "description": "extension: whether the entities stay editable once installed." },
                "out": { "type": "string", "description": "The file to write, relative to the solution root." },
                "overwrite": { "type": "boolean", "default": false },
            }),
            &["action", "out"],
            false,
        ),
        tool(
            "import",
            "Import into the server as Composer's Import/Export does: an export file of the solution (XML, or a zip of them), or a source-control tree in a file repository. A dry run unless dry_run is false: a file's plan lists what it adds and what it replaces; a source-control plan is the server's own diff. The server's property values and configuration table rows are kept unless the overwrite flags say otherwise.",
            json!({
                "action": { "type": "string", "enum": ["file", "source_control"] },
                "file": { "type": "string", "description": "file: relative to the solution root." },
                "repository": { "type": "string", "description": "source_control: the file repository." },
                "path": { "type": "string", "description": "source_control: the tree's folder in it." },
                "overwrite_properties": { "type": "boolean", "default": false },
                "overwrite_tables": { "type": "boolean", "default": false },
                "dry_run": { "type": "boolean", "default": true },
                "profile": profile_arg(),
            }),
            &["action"],
            false,
        ),
        tool(
            "settings",
            "Read the server's subsystem settings (Composer: Browse > Subsystems): list the subsystems, show one with every setting, its value and description, or search every setting by name or description. Read-only; PASSWORD values are never shown.",
            json!({
                "action": { "type": "string", "enum": ["list", "show", "search"], "default": "list" },
                "subsystem": { "type": "string", "description": "show: a subsystem, such as Logging or LoggingSubsystem." },
                "text": { "type": "string", "description": "search: part of a setting's name or description." },
                "profile": profile_arg(),
            }),
            &[],
            true,
        ),
        tool(
            "catalog",
            "The repository's offline service catalog: callable services by entity, their parameters, result, description, origin and whether code exists. Summary returns at most 50 services; detail returns all.",
            json!({
                "entity": { "type": "string", "description": "One entity, full name or its last dotted segment." },
                "project": { "type": "string", "description": "Narrow to one project of the solution." },
                "text": { "type": "string", "description": "Case-insensitive match over service names, parameter names and descriptions; use entity to narrow to one entity." },
                "detail": detail(),
            }),
            &[],
            true,
        ),
        tool(
            "impact",
            "What changing an entity, or one service, property or field of it, would reach: the Things, templates, shapes, mashups and projects that depend on it, directly or through others, each at the strength of its weakest reference (structural: declared in the XML or twaco.toml; resolved: a static name in a script or a mashup binding; review: a string that looks like the name, for a person to judge). Offline and read-only. It cannot see references built at run time or outside the repository; `complete` says whether every input was read and `unreadable` lists what was not. Summary leaves the chain to each dependent out; detail includes it.",
            json!({
                "entity": { "type": "string", "description": "Collection/Name, a full name, or its last dotted segment." },
                "member": { "type": "string", "description": "A service, property or field of the entity: ask only about what names it." },
                "min_confidence": { "type": "string", "enum": ["structural", "resolved", "review"], "default": "review", "description": "The weakest reference to follow." },
                "depth": { "type": "integer", "minimum": 1, "description": "How many references away to look; omit for no limit." },
                "format": { "type": "string", "enum": ["json", "dot"], "default": "json", "description": "dot returns the dependents as a Graphviz graph in `dot`." },
                "detail": detail(),
            }),
            &["entity"],
            true,
        ),
        tool(
            "unused",
            "Entities nothing reaches: Things, templates, shapes and DataShapes with no chain of references from an entry point (what twaco.toml deploys, every mashup, anything that runs on events, and what `[unused] keep` names). Advisory and read-only: it deletes nothing, and an entity used only from outside the repository (a REST client, a connected system) looks unused, so list those under `[unused] keep`. `complete` says whether every input was read; `keep_unmatched` lists keep patterns that match nothing.",
            json!({
                "min_confidence": { "type": "string", "enum": ["structural", "resolved", "review"], "default": "review", "description": "The weakest reference that counts as use; a stronger minimum reports more entities." },
                "collection": { "type": "string", "enum": ["Things", "ThingTemplates", "ThingShapes", "DataShapes"], "description": "Judge one collection only." },
                "detail": detail(),
            }),
            &[],
            true,
        ),
        tool(
            "docs",
            "The solution written down from the repository: the projects and their deploy order, how Things, templates and shapes inherit, every service with its signature, the DataShapes with their fields and where they are used, and the references that only look like a name and need a person's judgement. Offline and read-only; it has no dates, so regenerating it and diffing shows what changed. Permissions are not read yet, and references built at run time are not seen; `complete` says whether every input was read. Returns the document as JSON in `document` and as Markdown in `markdown`. Summary gives service and field counts; detail gives every signature and field.",
            json!({
                "detail": detail(),
            }),
            &[],
            true,
        ),
        tool(
            "guide",
            "Knowledge for working on this solution: twaco's workflow, the ThingWorx platform's verified-live quirks, the service-code reference, and the solution's own AGENTS.md, CLAUDE.md and docs/. Search before a live import, a hand-written mashup binding, a configuration-table change, or a service that introspects metadata or touches JSON. list: the topics; search: the best-matching sections; read: a topic (a long one gives its outline) or one section by heading.",
            json!({
                "action": { "type": "string", "enum": ["list", "search", "read"], "default": "search" },
                "text": { "type": "string", "description": "search: words, such as \"AddMember group\" or \"configuration table row replaced\"." },
                "topic": { "type": "string", "description": "read: a topic id from list or search, such as quirks or docs/DEVELOPER_GUIDE." },
                "section": { "type": "string", "description": "read: a section heading, or a part of it that only one heading has." },
                "limit": { "type": "integer", "minimum": 1, "default": 8 },
            }),
            &[],
            true,
        ),
        tool(
            "help_search",
            "Search the ThingWorx Platform help center for the server's version (or another): pages holding every word, best first, with title, path, summary and address. It explains concepts and how-tos; for one service's parameters, the editor types (`types`) are better.",
            json!({
                "query": { "type": "string", "description": "Words, as in the help's own search box. Code such as Resources[\"InfoTableFunctions\"] is split into its words." },
                "limit": { "type": "integer", "minimum": 1, "default": 10 },
                "version": { "type": "string", "description": "A help release such as 10.1; default: the server's own." },
                "refresh": { "type": "boolean", "default": false, "description": "Download the index again instead of using the cache." },
                "profile": profile_arg(),
            }),
            &["query"],
            true,
        ),
        tool(
            "help_page",
            "Read one ThingWorx Platform help page as Markdown, from a path or address that help_search returned. Long pages: ask for one section by heading; the result lists every heading.",
            json!({
                "page": { "type": "string", "description": "A path such as ThingWorx/Help/Composer/Things/ThingServices/QueryParameterforQueryServices.html, or its address." },
                "section": { "type": "string", "description": "Only the part under the first heading containing this text." },
                "max_chars": { "type": "integer", "minimum": 1000, "default": 20000 },
                "version": { "type": "string", "description": "A help release such as 10.1; default: the one in the address, else the server's own." },
                "refresh": { "type": "boolean", "default": false },
                "profile": profile_arg(),
            }),
            &["page"],
            true,
        ),
        tool(
            "javadoc",
            "Search or read the ThingWorx Platform API 10.1.0 Javadoc as Markdown. search ranks class and member simple names exact, prefix, then contains. class gives the class description and method summaries; member gives every overload with parameters, returns and throws. Useful for the Java methods of objects scripts call and Resource service parameter descriptions.",
            json!({
                "action": { "type": "string", "enum": ["search", "class"] },
                "name": { "type": "string", "description": "A search name, or a simple/qualified class name." },
                "member": { "type": "string", "description": "class: return full details for every overload of this member." },
                "limit": { "type": "integer", "minimum": 1, "default": 10 },
                "refresh": { "type": "boolean", "default": false },
            }),
            &["action", "name"],
            true,
        ),
        tool(
            "call",
            "Call a ThingWorx service. A service can write, and twaco cannot tell which do, so this is a dry run unless dry_run is false. A bare target is a Thing; Collection/Name reaches templates, shapes, resources and subsystems.",
            json!({
                "target": { "type": "string", "description": "Collection/Name, or an entity of the solution by full or last-segment name (Manager), or a platform Thing's name." },
                "service": { "type": "string" },
                "parameters": { "type": "object", "default": {} },
                "dry_run": { "type": "boolean", "default": true },
                "timeout_seconds": { "type": "integer", "minimum": 1, "default": 120 },
                "with_logs": { "type": "boolean", "default": false, "description": "Also return what the call wrote to ScriptLog and ApplicationLog, even when it fails. Waits up to 3 s for late entries. ScriptLog at WARN records no logger.info/debug; see log_level." },
                "profile": profile_arg(),
                "detail": detail(),
            }),
            &["target", "service"],
            false,
        ),
    ]
}
