//! The database half of a rename: a guarded, re-runnable SQL script for DBConnection tables.
//!
//! twaco never opens a database. It writes the script, says to run it before the import (the
//! platform's `DeployComponent` creates tables and never renames one, so importing first would leave
//! the data behind in the old names), and offers `twaco db run` to run it through the platform.
//! The names follow what DBConnection does: a table is the lowercased short name of its DataShape,
//! a column the lowercased field name, and the objects it creates take their names from both
//! (`<table>_pkey`, `<table>_<cols>_idx`, `<table>_<col>_fk`, `<table>_<col>_seq`). Postgres keeps
//! those old names across a rename, so the script renames them too.

use std::fmt::Write;

/// A table whose name changes because its DataShape's short name changes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TableRename {
    pub old_table: String,
    pub new_table: String,
    /// Each index of the table, as its lowercased column names.
    pub indexes: Vec<Vec<String>>,
    /// The lowercased columns that carry a foreign key.
    pub foreign_keys: Vec<String>,
}

/// A column renamed in a table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnRename {
    pub table: String,
    pub old: String,
    pub new: String,
    pub indexes: Vec<Vec<String>>,
    pub foreign_keys: Vec<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Migration {
    pub date: String,
    pub title: String,
    pub tables: Vec<TableRename>,
    pub columns: Vec<ColumnRename>,
    /// Old entity name -> new, replaced inside the text columns of every table in `backed_tables`.
    pub replacements: Vec<(String, String)>,
    /// Every DBConnection table, under the names it has once the table renames above ran.
    pub backed_tables: Vec<String>,
    /// Things a person must check, printed as comments.
    pub notes: Vec<String>,
}

impl Migration {
    pub fn is_empty(&self) -> bool {
        self.tables.is_empty() && self.columns.is_empty() && self.replacements.is_empty()
    }
}

/// The file name for a migration: `<date>-rename-<what>.sql`, safe on every platform.
pub fn file_name(date: &str, label: &str) -> String {
    let safe: String = label
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect();
    format!("{date}-rename-{safe}.sql")
}

/// A SQL string literal.
fn literal(text: &str) -> String {
    format!("'{}'", text.replace('\'', "''"))
}

/// A SQL identifier, quoted.
fn ident(text: &str) -> String {
    format!("\"{}\"", text.replace('"', "\"\""))
}

fn index_name(table: &str, columns: &[String]) -> String {
    format!("{table}_{}_idx", columns.join("_"))
}

/// Render the script.
pub fn render(migration: &Migration) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "-- {}", migration.title);
    let _ = writeln!(out, "--");
    let _ = writeln!(out, "-- Generated by twaco rename on {}.", migration.date);
    let _ = writeln!(out, "--");
    let _ = writeln!(out, "-- Run this BEFORE importing the renamed entities. DeployComponent creates tables but never");
    let _ = writeln!(out, "-- renames one, so importing first would leave UpdateDatabaseSchema creating new empty tables");
    let _ = writeln!(out, "-- while the data stays behind in the old ones.");
    let _ = writeln!(out, "--");
    let _ = writeln!(out, "-- Back the affected tables up first, for example:");
    let tables: Vec<&str> = migration
        .tables
        .iter()
        .map(|rename| rename.old_table.as_str())
        .chain(migration.columns.iter().map(|rename| rename.table.as_str()))
        .collect();
    let dump: String = tables.iter().map(|table| format!(" -t {table}")).collect();
    let _ = writeln!(out, "--     pg_dump -d <database>{dump} > backup.sql");
    let _ = writeln!(out, "--");
    let _ = writeln!(
        out,
        "-- Run it as one atomic script with `twaco db run <this file> --apply`, or with psql:"
    );
    let _ = writeln!(out, "--     psql -v ON_ERROR_STOP=1 -f <this file>");
    let _ = writeln!(out, "--");
    let _ = writeln!(
        out,
        "-- Safe to re-run: every statement is guarded and does nothing once it has been applied."
    );
    for note in &migration.notes {
        let _ = writeln!(out, "-- NOTE: {note}");
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "BEGIN;");

    for rename in &migration.tables {
        let (old, new) = (&rename.old_table, &rename.new_table);
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "-- Table {old} -> {new}. DBConnection names a table for its DataShape, lowercased."
        );
        let _ = writeln!(
            out,
            "ALTER TABLE IF EXISTS {} RENAME TO {};",
            ident(old),
            ident(new)
        );
        let _ = writeln!(
            out,
            "-- Postgres keeps the old names of what belongs to the table: rename them so a later"
        );
        let _ = writeln!(out, "-- UpdateDatabaseSchema finds the names it expects.");
        let _ = writeln!(
            out,
            "ALTER INDEX IF EXISTS {} RENAME TO {};",
            ident(&format!("{old}_pkey")),
            ident(&format!("{new}_pkey"))
        );
        for columns in &rename.indexes {
            let _ = writeln!(
                out,
                "ALTER INDEX IF EXISTS {} RENAME TO {};",
                ident(&index_name(old, columns)),
                ident(&index_name(new, columns))
            );
        }
        for column in &rename.foreign_keys {
            let _ = write!(
                out,
                "{}",
                rename_constraint(
                    new,
                    &format!("{old}_{column}_fk"),
                    &format!("{new}_{column}_fk")
                )
            );
        }
        let _ = writeln!(
            out,
            "ALTER SEQUENCE IF EXISTS {} RENAME TO {};  -- the primary key's sequence, when the key is uid",
            ident(&format!("{old}_uid_seq")),
            ident(&format!("{new}_uid_seq"))
        );
    }

    for rename in &migration.columns {
        let table = &rename.table;
        let (old, new) = (&rename.old, &rename.new);
        let _ = writeln!(out);
        let _ = writeln!(out, "-- Column {table}.{old} -> {new}. DBConnection names a column for its field, lowercased.");
        let _ = writeln!(out, "DO $$");
        let _ = writeln!(out, "BEGIN");
        let _ = writeln!(
            out,
            "    IF EXISTS (SELECT 1 FROM information_schema.columns"
        );
        let _ = writeln!(out, "               WHERE table_schema = current_schema() AND table_name = {} AND column_name = {})", literal(table), literal(old));
        let _ = writeln!(
            out,
            "       AND NOT EXISTS (SELECT 1 FROM information_schema.columns"
        );
        let _ = writeln!(out, "               WHERE table_schema = current_schema() AND table_name = {} AND column_name = {}) THEN", literal(table), literal(new));
        let _ = writeln!(
            out,
            "        ALTER TABLE {} RENAME COLUMN {} TO {};",
            ident(table),
            ident(old),
            ident(new)
        );
        let _ = writeln!(out, "    END IF;");
        let _ = writeln!(out, "END $$;");
        for columns in rename
            .indexes
            .iter()
            .filter(|columns| columns.contains(old))
        {
            let renamed: Vec<String> = columns
                .iter()
                .map(|column| {
                    if column == old {
                        new.clone()
                    } else {
                        column.clone()
                    }
                })
                .collect();
            let _ = writeln!(
                out,
                "ALTER INDEX IF EXISTS {} RENAME TO {};",
                ident(&index_name(table, columns)),
                ident(&index_name(table, &renamed))
            );
        }
        if rename.foreign_keys.contains(old) {
            let _ = write!(
                out,
                "{}",
                rename_constraint(
                    table,
                    &format!("{table}_{old}_fk"),
                    &format!("{table}_{new}_fk")
                )
            );
        }
        let _ = writeln!(
            out,
            "ALTER SEQUENCE IF EXISTS {} RENAME TO {};  -- only when the column is a generated key",
            ident(&format!("{table}_{old}_seq")),
            ident(&format!("{table}_{new}_seq"))
        );
    }

    if !migration.replacements.is_empty() && !migration.backed_tables.is_empty() {
        let list: Vec<String> = migration
            .backed_tables
            .iter()
            .map(|table| literal(table))
            .collect();
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "-- Rows name entities by their full name (a card stores the mashup it renders)."
        );
        let _ = writeln!(
            out,
            "-- This is a plain substring replace in every text column of the DBConnection tables:"
        );
        for (old, new) in &migration.replacements {
            let _ = writeln!(out, "--     {old} -> {new}");
        }
        let _ = writeln!(out, "DO $$");
        let _ = writeln!(out, "DECLARE");
        let _ = writeln!(out, "    col record;");
        let _ = writeln!(out, "BEGIN");
        let _ = writeln!(out, "    FOR col IN");
        let _ = writeln!(
            out,
            "        SELECT table_name, column_name FROM information_schema.columns"
        );
        let _ = writeln!(
            out,
            "        WHERE table_schema = current_schema() AND table_name IN ({})",
            list.join(", ")
        );
        let _ = writeln!(
            out,
            "          AND data_type IN ('character varying', 'text')"
        );
        let _ = writeln!(out, "    LOOP");
        for (old, new) in &migration.replacements {
            let _ = writeln!(
                out,
                "        EXECUTE format('UPDATE %I SET %I = replace(%I, %L, %L) WHERE position(%L in %I) > 0',"
            );
            let _ = writeln!(
                out,
                "                       col.table_name, col.column_name, col.column_name, {}, {}, {}, col.column_name);",
                literal(old),
                literal(new),
                literal(old)
            );
        }
        let _ = writeln!(out, "    END LOOP;");
        let _ = writeln!(out, "END $$;");
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "COMMIT;");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "-- Check afterwards (expect the new names and no old ones):"
    );
    let _ = writeln!(
        out,
        "--     SELECT table_name, column_name FROM information_schema.columns"
    );
    let _ = writeln!(
        out,
        "--     WHERE table_schema = current_schema() ORDER BY 1, 2;"
    );
    out
}

/// A guarded `ALTER TABLE ... RENAME CONSTRAINT`: Postgres has no `IF EXISTS` for it.
fn rename_constraint(table: &str, old: &str, new: &str) -> String {
    format!(
        "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = {}) THEN ALTER TABLE {} RENAME CONSTRAINT {} TO {}; END IF; END $$;\n",
        literal(old),
        ident(table),
        ident(old),
        ident(new)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn column() -> Migration {
        Migration {
            date: "2026-10-02".into(),
            title: "Rename field Acme.Dashboards.UserName to OwnerName".into(),
            columns: vec![ColumnRename {
                table: "dashboards".into(),
                old: "username".into(),
                new: "ownername".into(),
                indexes: vec![
                    vec!["username".into()],
                    vec!["dashboard_uid".into(), "username".into()],
                ],
                foreign_keys: vec!["username".into()],
            }],
            ..Default::default()
        }
    }

    #[test]
    fn a_column_rename_is_guarded_and_tidies_the_derived_names() {
        let sql = render(&column());
        assert!(sql.contains("BEGIN;") && sql.trim_end().lines().any(|line| line == "COMMIT;"));
        // Only renamed when the old column exists and the new one does not.
        assert!(
            sql.contains("AND NOT EXISTS (SELECT 1 FROM information_schema.columns"),
            "{sql}"
        );
        assert!(
            sql.contains("column_name = 'username')")
                && sql.contains("column_name = 'ownername') THEN"),
            "{sql}"
        );
        assert!(
            sql.contains("ALTER TABLE \"dashboards\" RENAME COLUMN \"username\" TO \"ownername\";"),
            "{sql}"
        );
        // Both indexes that list the column, under the names DBConnection gave them.
        assert!(sql.contains("ALTER INDEX IF EXISTS \"dashboards_username_idx\" RENAME TO \"dashboards_ownername_idx\";"), "{sql}");
        assert!(sql.contains("ALTER INDEX IF EXISTS \"dashboards_dashboard_uid_username_idx\" RENAME TO \"dashboards_dashboard_uid_ownername_idx\";"), "{sql}");
        assert!(
            sql.contains(
                "RENAME CONSTRAINT \"dashboards_username_fk\" TO \"dashboards_ownername_fk\""
            ),
            "{sql}"
        );
        assert!(sql.contains("before importing") || sql.contains("BEFORE importing"));
    }

    #[test]
    fn a_table_rename_moves_the_key_index_foreign_key_and_sequence_names() {
        let migration = Migration {
            date: "2026-10-02".into(),
            title: "Rename entity Acme.Dashboards".into(),
            tables: vec![TableRename {
                old_table: "dashboards".into(),
                new_table: "boards".into(),
                indexes: vec![vec!["username".into()]],
                foreign_keys: vec!["owner_uid".into()],
            }],
            ..Default::default()
        };
        let sql = render(&migration);
        assert!(
            sql.contains("ALTER TABLE IF EXISTS \"dashboards\" RENAME TO \"boards\";"),
            "{sql}"
        );
        assert!(
            sql.contains("\"dashboards_pkey\" RENAME TO \"boards_pkey\""),
            "{sql}"
        );
        assert!(
            sql.contains("\"dashboards_username_idx\" RENAME TO \"boards_username_idx\""),
            "{sql}"
        );
        assert!(sql.contains("ALTER TABLE \"boards\" RENAME CONSTRAINT \"dashboards_owner_uid_fk\" TO \"boards_owner_uid_fk\""), "{sql}");
        assert!(
            sql.contains("\"dashboards_uid_seq\" RENAME TO \"boards_uid_seq\""),
            "{sql}"
        );
    }

    #[test]
    fn row_data_is_replaced_in_the_text_columns_of_the_backed_tables_with_quoted_literals() {
        let migration = Migration {
            date: "2026-10-02".into(),
            title: "Rename prefix".into(),
            replacements: vec![
                ("Acme.Old".into(), "Acme.New".into()),
                ("It's".into(), "Its".into()),
            ],
            backed_tables: vec!["dashboards".into(), "dashboardcards".into()],
            ..Default::default()
        };
        let sql = render(&migration);
        assert!(
            sql.contains("table_name IN ('dashboards', 'dashboardcards')"),
            "{sql}"
        );
        assert!(
            sql.contains("data_type IN ('character varying', 'text')"),
            "{sql}"
        );
        assert!(sql.contains("'Acme.Old', 'Acme.New', 'Acme.Old'"), "{sql}");
        assert!(
            sql.contains("'It''s', 'Its', 'It''s'"),
            "a quote in a name is doubled: {sql}"
        );
        assert!(sql.contains("plain substring replace"));
    }

    #[test]
    fn nothing_to_say_is_empty_and_file_names_are_safe() {
        assert!(Migration::default().is_empty());
        assert!(!column().is_empty());
        assert_eq!(
            file_name("2026-10-02", "field-Acme.D.UserName-to-OwnerName"),
            "2026-10-02-rename-field-Acme.D.UserName-to-OwnerName.sql"
        );
        assert_eq!(
            file_name("2026-10-02", "a b/c"),
            "2026-10-02-rename-a-b-c.sql"
        );
    }
}
